[package]
name = "tasklist"
version = "0.1.0"
authors = ["Malte Brandy <malte.brandy@maralorn.de>"]

[dependencies]
task-hookrs = "0.3.0"
uuid = { version = "0.4", features = ["serde"] }
gtk = { version = "0.1.3", default-features = false,features = ["v3_22"]}

